export const CREATE_GUEST_REQUEST = "CREATE_GUEST_REQUEST";
export const CREATE_GUEST_RECEIVE = "CREATE_GUEST_RECEIVE";
export const CREATE_GUEST_FAILURE = "CREATE_GUEST_FAILURE";
export const RESET_CREATE_GUEST = "RESET_CREATE_GUEST";


export const EDIT_GUEST_REQUEST = "EDIT_GUEST_REQUEST";
export const EDIT_GUEST_RECEIVE = "EDIT_GUEST_RECEIVE";
export const EDIT_GUEST_FAILURE = "EDIT_GUEST_FAILURE";
export const RESET_EDIT_GUEST = "RESET_EDIT_GUEST";